server {
    listen 70;
    server_name _;

    root /app/dist/my-page/browser;
    index index.html;

    # Serve static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }

    # # Optional: cache static assets aggressively
    # location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
    #     expires 1y;
    #     add_header Cache-Control "public, immutable";
    #     try_files $uri =404;
    # }

    # # Optional: disable cache for index.html
    # location = /index.html {
    #     add_header Cache-Control "no-cache";
    # }
}
